function [act_eq, inh_eq, growth_eq] = get_eq_latex()

  addpath('./settings');

  act_eq = strcat([
    '$\displaystyle \frac{\partial a}{\partial t} = ' ...
    latex(vpa(sym(@(a, h) act_eq_rest(a, h)))) ...
    ' + ' ...
    num2str(act_eq_diffu()) ...
    ' \frac{\partial^2 a}{\partial x^2}' ...
    '$'
  ]);
  inh_eq = strcat([
    '$\displaystyle \frac{\partial h}{\partial t} = ' ...
    latex(vpa(sym(@(a, h) inh_eq_rest(a, h)))) ...
    ' + ' ...
    num2str(inh_eq_diffu()) ...
    ' \frac{\partial^2 h}{\partial x^2}' ...
    '$'
  ]);
  growth_eq = strcat([
    '$\displaystyle l(t) = ' ...
    num2str(init_length()) ...
    ' + ' ...
    num2str(growth_velocity()) ...
    't' ...
    '$'
  ]);

end
