function [act_eq, inh_eq, growth_eq] = get_eq_latex()

  addpath('./settings');

  act_eq = strcat([
    '$\displaystyle a_t = ' ...
    latex(vpa(sym(@(a, h) act_eq_rest(a, h)))) ...
    ' + ' ...
    num2str(act_eq_diffu()) ...
    ' a_{xx}' ...
    '$'
  ]);
  inh_eq = strcat([
    '$\displaystyle h_t = ' ...
    latex(vpa(sym(@(a, h) inh_eq_rest(a, h)))) ...
    ' + ' ...
    num2str(inh_eq_diffu()) ...
    ' h_{xx}' ...
    '$'
  ]);
  growth_eq = strcat([
    '$\displaystyle l(t) = ' ...
    num2str(init_length()) ...
    ' + ' ...
    num2str(growth_velocity()) ...
    't' ...
    '$'
  ]);

end
