function drawWhiteRectangleSimulatingGrowth( ...
  initialRootLength, ...
  tipVelocity, ...
  curTime, ...
  spatialDomainSize, ...
  rootWidth, ...
  rootLowerLeftOffsetFromLowerLeftOfFigure)

  rectLowerLeftX = rootLowerLeftOffsetFromLowerLeftOfFigure;
  rectLowerLeftY = initialRootLength + tipVelocity * curTime;
  
  if (rectLowerLeftY < spatialDomainSize)
    rectangle( ...
      'Position', [rectLowerLeftX rectLowerLeftY ...
        rootWidth (spatialDomainSize - rectLowerLeftY)], ...
      'EdgeColor', 'white', ...
      'FaceColor', 'white');
  end