for i = 1:256

  actFigPath = ...
    fullfile( ...
      fileparts(mfilename('fullpath')), ...
      'multiparam_results', ...
      strcat(num2str(i), '-act.fig') ...
    );
  inhFigPath = ...
    fullfile( ...
      fileparts(mfilename('fullpath')), ...
      'multiparam_results', ...
      strcat(num2str(i), '-inh.fig') ...
    );

  actPngSavePath = ...
    fullfile( ...
      fileparts(mfilename('fullpath')), ...
      'asset', ...
      'multiparam_results', ...
      strcat(num2str(i), '-act.png') ...
    );
  inhPngSavePath = ...
    fullfile( ...
      fileparts(mfilename('fullpath')), ...
      'asset', ...
      'multiparam_results', ...
      strcat(num2str(i), '-inh.png') ...
    );

  openfig(actFigPath, 'invisible');
  saveas(gcf, actPngSavePath);
  openfig(inhFigPath, 'invisible');
  saveas(gcf, inhPngSavePath);

end
