function indexes = findConcenPeaks(concenSolutions)

globalMax = max(concenSolutions(:));
globalMin = min(concenSolutions(:));

computeSpatialIntervalsAtThisTMeshIndex = size(concenSolutions, 1);

concensAtTheTMeshIndex = ...
  concenSolutions(computeSpatialIntervalsAtThisTMeshIndex, :);

[~, indexes] = findpeaks( ...
  concensAtTheTMeshIndex, ...
  'MinPeakProminence', (globalMax - globalMin) * 0.1, ... 
  'MinPeakHeight', globalMax * 0.5 + globalMin * 0.5 ...
);
