function plots

spatialDomainSize = 10000; % micrometers
spatialDomainStep = 100; % micrometers
timeDomainSize = 100000; % seconds
timeDomainStep = 50; % seconds

actBaseProd = 0.0033;
actDecayCoeff = 0.00019; % the mu in the differential equations
actDenominatorDefault = 1;
actDiffuCoeff = 0.001; % the D_a
actSourceDensity = 0.00018; % the rho_a
tipVelocity = 0.11574; % This is about 1cm growth per day.
inhDecayCoeff = 0.00025; % the nu
inhDiffuCoeff = 20; % the D_h
inhSourceDensity = 0.00001; % the rho_h

pdeSolutions = getPdeSolutions( ...
  actBaseProd, ...
  actDecayCoeff, ...
  actDenominatorDefault, ...
  actDiffuCoeff, ...
  actSourceDensity, ...
  tipVelocity, ...
  inhDecayCoeff, ...
  inhDiffuCoeff, ...
  inhSourceDensity, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep);

actConcenSolutions = pdeSolutions(:,:,1);
inhConcenSolutions = pdeSolutions(:,:,2);

getActOrInhConcens3DFigure( ...
  [
    'a(x,t) : ' ...
    ' v=',num2str(tipVelocity), ...
    ' c=',num2str(actBaseProd), ...
    ' \mu=',num2str(actDecayCoeff), ...
    ' h_0=',num2str(actDenominatorDefault), ...
    ' D_a=',num2str(actDiffuCoeff), ...
    ' \rho_a=',num2str(actSourceDensity), ...
    ' \nu=',num2str(inhDecayCoeff), ...
    ' D_h=',num2str(inhDiffuCoeff), ...
    ' \rho_h=',num2str(inhSourceDensity) ...
  ], ...
  actConcenSolutions, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep);

getActOrInhConcens3DFigure( ...
  [
    'h(x,t) : ' ...
    ' v=',num2str(tipVelocity), ...
    ' c=',num2str(actBaseProd), ...
    ' \mu=',num2str(actDecayCoeff), ...
    ' h_0=',num2str(actDenominatorDefault), ...
    ' D_a=',num2str(actDiffuCoeff), ...
    ' \rho_a=',num2str(actSourceDensity), ...
    ' \nu=',num2str(inhDecayCoeff), ...
    ' D_h=',num2str(inhDiffuCoeff), ...
    ' \rho_h=',num2str(inhSourceDensity) ...
  ], ...
  inhConcenSolutions, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep);

produceAnimationOfConcensDiffusion( ...
  [
    ' v=', num2str(tipVelocity), ...
    ' c=', num2str(actBaseProd), ...
    ' \mu=', num2str(actDecayCoeff), ...
    ' h_0=', num2str(actDenominatorDefault), ...
    ' D_a=', num2str(actDiffuCoeff), ...
    ' \rho_a=', num2str(actSourceDensity), ...
    ' \nu=', num2str(inhDecayCoeff), ...
    ' D_h=', num2str(inhDiffuCoeff), ...
    ' \rho_h=', num2str(inhSourceDensity) ...
  ], ...
  actConcenSolutions, ...
  inhConcenSolutions, ...
  timeDomainSize, ...
  timeDomainStep, ...
  spatialDomainSize, ...
  spatialDomainStep);
