function plots

timeDomainSize = 100000; % seconds
timeDomainStep = 50; % seconds

actDecayCoeff = 0.00019; % the mu in the differential equations
actDenominatorDefault = 1;
actDiffuCoeff = 1; % the D_a
actSourceDensity = 0.02; % the rho_a
initialRootLength = 500; % in micrometers
tipVelocity = 0.11574; % This is about 1cm growth per day.
inhDecayCoeff = 0.0025; % the nu
inhDiffuCoeff = 250; % the D_h
inhSourceDensity = 0.0001; % the rho_h

[spatialDomainSize, spatialDomainStep] = ... % The unit is micrometers.
  getGoodSpatialDomainSizeAndStep(timeDomainSize, timeDomainStep, tipVelocity);

pdeSolutions = getPdeSolutions( ...
  actDecayCoeff, ...
  actDenominatorDefault, ...
  actDiffuCoeff, ...
  actSourceDensity, ...
  tipVelocity, ...
  inhDecayCoeff, ...
  inhDiffuCoeff, ...
  inhSourceDensity, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep);

actConcenSolutions = pdeSolutions(:,:,1);
inhConcenSolutions = pdeSolutions(:,:,2);

getActOrInhConcens3DFigure( ...
  [
    'a(x,t) : ' ...
    ' v=',num2str(tipVelocity), ...
    ' \mu=',num2str(actDecayCoeff), ...
    ' h_0=',num2str(actDenominatorDefault), ...
    ' D_a=',num2str(actDiffuCoeff), ...
    ' \rho_a=',num2str(actSourceDensity), ...
    ' \nu=',num2str(inhDecayCoeff), ...
    ' D_h=',num2str(inhDiffuCoeff), ...
    ' \rho_h=',num2str(inhSourceDensity) ...
  ], ...
  actConcenSolutions, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep, ...
  tipVelocity, ...
  'tip');

getActOrInhConcens3DFigure( ...
  [
    'h(x,t) : ' ...
    ' v=',num2str(tipVelocity), ...
    ' \mu=',num2str(actDecayCoeff), ...
    ' h_0=',num2str(actDenominatorDefault), ...
    ' D_a=',num2str(actDiffuCoeff), ...
    ' \rho_a=',num2str(actSourceDensity), ...
    ' \nu=',num2str(inhDecayCoeff), ...
    ' D_h=',num2str(inhDiffuCoeff), ...
    ' \rho_h=',num2str(inhSourceDensity) ...
  ], ...
  inhConcenSolutions, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  timeDomainSize, ...
  timeDomainStep, ...
  tipVelocity, ...
  'tip');

produceAnimationOfConcensDiffusion( ...
  [
    ' v=', num2str(tipVelocity), ...
    ' \mu=', num2str(actDecayCoeff), ...
    ' h_0=', num2str(actDenominatorDefault), ...
    ' D_a=', num2str(actDiffuCoeff), ...
    ' \rho_a=', num2str(actSourceDensity), ...
    ' \nu=', num2str(inhDecayCoeff), ...
    ' D_h=', num2str(inhDiffuCoeff), ...
    ' \rho_h=', num2str(inhSourceDensity) ...
  ], ...
  actConcenSolutions, ...
  inhConcenSolutions, ...
  timeDomainSize, ...
  timeDomainStep, ...
  spatialDomainSize, ...
  spatialDomainStep, ...
  tipVelocity, ...
  initialRootLength);
