function plot3d()

  addpath('./lib');
  addpath('./settings');

  [a_sol, h_sol, t_mesh_secs, x_mesh] = solve(struct( ...
    'act_bound_open_end', @act_bound_open_end, ...
    'act_eq_diffu', @act_eq_diffu, ...
    'act_eq_rest', @act_eq_rest, ...
    'act_init', @act_init, ...
    'growth', @growth, ...
    'inh_bound_open_end', @inh_bound_open_end, ...
    'inh_eq_diffu', @inh_eq_diffu, ...
    'inh_eq_rest', @inh_eq_rest, ...
    'inh_init', @inh_init, ...
    'time_max', @time_max ...
  ));

  figure;
  t_mesh_hours = t_mesh_secs / 60 / 60; % y-axis unit is hours, not seconds
  surf(x_mesh, t_mesh_hours, a_sol, ...
    'EdgeColor', 'none'); % Turn off the meshes on the graph.
  title('Yolo!');
  xlabel('Distance from the open end (micro-m)');
  ylabel('Time (hours)');
  zlabel('Concentration (whatever unit)');
  view([0 90]); % Look at the 3D plot from atop (i.e. from z=infinity)
  axis tight; % Without this, there'll be some blank space around y-axis
  colorbar; % This adds a color legend.

end
