function preview()

  addpath('./lib');

  t_size_per_mesh = 200;
  y_size_per_mesh = 0.01;
  [a_sol, h_sol, t_mesh_secs, x_mesh] = ...
    solve_cacheless(t_size_per_mesh, y_size_per_mesh);

  a_fig = plot3d(a_sol, t_mesh_secs, x_mesh, ...
    'Simulation of $a(x,t)$ under the following equations:', ...
    500, 500, -250);
  h_fig = plot3d(h_sol, t_mesh_secs, x_mesh, ...
    'Simulation of $h(x,t)$ under the following equations:', ...
    500, 500, 250);

  if exist('../history', 'dir') ~= 7
    mkdir('../history');
  end
  time_now_str = datestr(datetime('now'), 'yyyymmdd-HHMMSS');
  saveas( ...
    a_fig, ...
    strcat('../history/', time_now_str, '-act') ...
  );
  saveas( ...
    h_fig, ...
    strcat('../history/', time_now_str, '-inh') ...
  );

end
